# Generated by Django 3.2.5 on 2021-08-01 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0015_auto_20210727_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('bride_or_groom_name', models.CharField(blank=True, max_length=255, null=True)),
                ('house_name', models.CharField(max_length=255)),
                ('post', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(max_length=255)),
                ('booking_date', models.DateTimeField()),
                ('contact1', models.IntegerField()),
                ('contact2', models.IntegerField()),
                ('stage_decoration', models.IntegerField(blank=True, null=True)),
                ('juice_counter', models.IntegerField(blank=True, null=True)),
                ('pop_corn_machine', models.IntegerField(blank=True, null=True)),
                ('sound_system', models.IntegerField(blank=True, null=True)),
                ('other_income_1', models.IntegerField(blank=True, null=True)),
                ('other_income_2', models.IntegerField(blank=True, null=True)),
                ('other_income_3', models.IntegerField(blank=True, null=True)),
                ('tota_income', models.IntegerField(blank=True, null=True)),
                ('cleaning_charge', models.IntegerField()),
                ('utensils_cleaning_charge', models.IntegerField()),
                ('parking_charge', models.IntegerField(blank=True, null=True)),
                ('waste_disposal_charge', models.IntegerField()),
                ('trasportaion_charge', models.IntegerField(blank=True, null=True)),
                ('detergents', models.IntegerField(blank=True, null=True)),
                ('maintanance', models.IntegerField(blank=True, null=True)),
                ('purchace_of_stock', models.IntegerField(blank=True, null=True)),
                ('generator_fule', models.IntegerField(blank=True, null=True)),
                ('electricity_bill', models.IntegerField(blank=True, null=True)),
                ('water_charge', models.IntegerField(blank=True, null=True)),
                ('other_expenditure_1', models.IntegerField(blank=True, null=True)),
                ('other_expenditure_2', models.IntegerField(blank=True, null=True)),
                ('other_expenditure_3', models.IntegerField(blank=True, null=True)),
                ('other_expenditure_4', models.IntegerField(blank=True, null=True)),
                ('total_expenditure', models.IntegerField()),
                ('event_date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingdata')),
            ],
        ),
    ]
