# Generated by Django 3.2.5 on 2021-08-01 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='bride_or_groom_name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='contact1',
        ),
        migrations.RemoveField(
            model_name='report',
            name='contact2',
        ),
        migrations.RemoveField(
            model_name='report',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='house_name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='location',
        ),
        migrations.RemoveField(
            model_name='report',
            name='name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='post',
        ),
    ]
