# Generated by Django 3.2.5 on 2021-08-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_auto_20210801_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
