# Generated by Django 3.2.5 on 2021-08-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_report_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='tota_income',
            new_name='total_income',
        ),
    ]
