# Generated by Django 3.2.5 on 2021-08-02 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_rename_tota_income_report_total_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_submition_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
