# Generated by Django 3.2.5 on 2021-07-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_balace_bookingdata_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdata',
            name='bride_or_groom_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
