# Generated by Django 3.2.5 on 2021-07-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bookingdata_bride_or_groom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdata',
            name='event_type',
            field=models.CharField(choices=[('Marriage-Day', 'Marriage- Day'), ('Meeitng', 'Meeting'), ('Reception', 'Reception')], default='marriage', max_length=255),
            preserve_default=False,
        ),
    ]
