# Generated by Django 3.2.5 on 2021-07-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_bookingdata_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdata',
            name='balance',
            field=models.IntegerField(null=True),
        ),
    ]
