# Generated by Django 3.2.5 on 2021-07-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_bookingdata_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingdata',
            options={'ordering': ('-booking_date',)},
        ),
        migrations.AddField(
            model_name='bookingdata',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
