# Generated by Django 3.2.5 on 2021-07-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20210726_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdata',
            name='event_type',
            field=models.CharField(choices=[('Marriage Function (Day)', 'Marriage Function (Day)'), ('Meeting', 'Meeting'), ('Reception(Evening)', 'Reception(Evening)')], max_length=255),
        ),
    ]
