# Generated by Django 3.2.5 on 2021-07-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_bookingdata_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdata',
            name='event_date',
            field=models.DateField(unique=True),
        ),
    ]
