# Generated by Django 3.2.5 on 2021-07-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_bookingdata_event_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingdata',
            options={'ordering': ('event_date',)},
        ),
        migrations.AddField(
            model_name='bookingdata',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
