# Generated by Django 3.2.5 on 2021-07-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdata',
            name='advance',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='balance',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='total_amount',
            field=models.PositiveIntegerField(default=40000),
        ),
    ]
