# Generated by Django 3.2.5 on 2021-07-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20210727_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdata',
            name='contact1',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='contact2',
            field=models.PositiveIntegerField(),
        ),
    ]
