# Generated by Django 3.2.5 on 2021-07-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20210727_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdata',
            name='contact1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='contact2',
            field=models.IntegerField(),
        ),
    ]
