# Generated by Django 3.2.5 on 2021-08-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_auto_20210801_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdata',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/'),
        ),
    ]
