# Generated by Django 3.2.5 on 2021-08-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_alter_bookingdata_id_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdata',
            name='kitchen_team_license',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/'),
        ),
    ]
