# Generated by Django 3.2.5 on 2021-08-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_alter_bookingdata_kitchen_team_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdata',
            name='id_proof',
        ),
    ]
