# Generated by Django 3.2.5 on 2021-07-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
    ]
