# Generated by Django 3.2.5 on 2021-07-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_portfolio_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
