# Generated by Django 3.2.5 on 2021-07-29 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_datecheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='datecheck',
            name='search_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
