# Generated by Django 3.2.5 on 2021-07-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_datecheck_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datecheck',
            name='id',
        ),
        migrations.AlterField(
            model_name='datecheck',
            name='contact',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
