# Generated by Django 3.2.5 on 2021-07-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210730_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='datecheck',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datecheck',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
