# Generated by Django 3.2.5 on 2021-07-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210730_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datecheck',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datecheck',
            name='name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
