# Generated by Django 3.2.5 on 2021-08-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210730_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allmessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
