# Generated by Django 3.2.5 on 2021-08-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_allmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmessages',
            name='message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='allmessages',
            name='subject',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
