# Generated by Django 3.2.5 on 2021-08-04 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210804_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmessages',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
