# Generated by Django 3.2.5 on 2021-08-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_allmessages_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Features',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
