# Generated by Django 3.2.5 on 2021-08-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('total_income', models.PositiveIntegerField()),
                ('total_expenditure', models.PositiveIntegerField()),
                ('total_gross', models.IntegerField()),
            ],
        ),
    ]
