# Generated by Django 3.2.5 on 2021-08-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystatistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlyreport',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='yearlyreport',
            name='total_expenditure',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='yearlyreport',
            name='total_gross',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='yearlyreport',
            name='total_income',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
