# Generated by Django 3.2.5 on 2021-08-02 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystatistics', '0002_auto_20210802_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='yearlyreport',
            name='year',
            field=models.ForeignKey(default=2021, on_delete=django.db.models.deletion.CASCADE, to='mystatistics.years'),
            preserve_default=False,
        ),
    ]
