# Generated by Django 3.2.5 on 2021-08-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystatistics', '0003_auto_20210802_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='years',
            old_name='Year',
            new_name='year',
        ),
    ]
