# Generated by Django 3.2.5 on 2021-08-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystatistics', '0006_alter_years_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlyreport',
            name='month_name',
            field=models.CharField(default='xxxx', max_length=50),
        ),
    ]
