# Generated by Django 3.2.5 on 2021-08-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_auto_20210805_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.IntegerField(default=1234567),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/'),
        ),
    ]
