# Generated by Django 3.2.5 on 2021-08-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_alter_user_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_proof',
        ),
        migrations.AddField(
            model_name='manager',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/'),
        ),
        migrations.AddField(
            model_name='manager',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='owners',
            name='is_owner',
            field=models.BooleanField(default=True),
        ),
    ]
