# Generated by Django 3.2.5 on 2021-08-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0005_auto_20210806_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owners',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Owners',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
