# Generated by Django 3.2.5 on 2021-08-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0007_manager_owners_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='is_owner',
        ),
        migrations.AddField(
            model_name='manager',
            name='is_manager',
            field=models.BooleanField(default=True),
        ),
    ]
