# Generated by Django 3.2.5 on 2021-08-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0008_auto_20210806_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='name',
            field=models.CharField(default='Manager', max_length=20),
        ),
    ]
